language: cpp
compiler: gcc
dist: trusty
osx_image: xcode9
sudo: required

os:
  - linux
  - osx

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis/build_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./.travis/build_osx.sh; fi
  - mkdir build
  - cd build
  - cmake -DDEBUG=0 ..

script: make -j8
